"""add_s3_columns_to_datasource

Revision ID: 27c65e8ac8e2
Revises: 5c1ca64f955a
Create Date: 2026-02-01 18:24:34.014864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c65e8ac8e2'
down_revision: Union[str, Sequence[str], None] = '5c1ca64f955a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('s3_key', sa.String(), nullable=True))
    op.add_column('data_sources', sa.Column('s3_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 's3_url')
    op.drop_column('data_sources', 's3_key')
    # ### end Alembic commands ###
