"""initial_tables

Revision ID: 5c1ca64f955a
Revises: 
Create Date: 2026-02-01 01:18:19.995110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c1ca64f955a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email', name='unique_email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('vectorstores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('index_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('embedding', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vectorstores_id'), 'vectorstores', ['id'], unique=False)
    op.create_index(op.f('ix_vectorstores_index_name'), 'vectorstores', ['index_name'], unique=True)
    op.create_index(op.f('ix_vectorstores_user_id'), 'vectorstores', ['user_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vector_store_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('mimetype', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vector_store_id'], ['vectorstores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.create_index(op.f('ix_data_sources_user_id'), 'data_sources', ['user_id'], unique=False)
    op.create_index(op.f('ix_data_sources_vector_store_id'), 'data_sources', ['vector_store_id'], unique=False)
    op.create_table('vector_indexes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vector_store_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['vector_store_id'], ['vectorstores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vector_indexes_document_id'), 'vector_indexes', ['document_id'], unique=False)
    op.create_index(op.f('ix_vector_indexes_id'), 'vector_indexes', ['id'], unique=False)
    op.create_index(op.f('ix_vector_indexes_vector_store_id'), 'vector_indexes', ['vector_store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vector_indexes_vector_store_id'), table_name='vector_indexes')
    op.drop_index(op.f('ix_vector_indexes_id'), table_name='vector_indexes')
    op.drop_index(op.f('ix_vector_indexes_document_id'), table_name='vector_indexes')
    op.drop_table('vector_indexes')
    op.drop_index(op.f('ix_data_sources_vector_store_id'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_user_id'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_vectorstores_user_id'), table_name='vectorstores')
    op.drop_index(op.f('ix_vectorstores_index_name'), table_name='vectorstores')
    op.drop_index(op.f('ix_vectorstores_id'), table_name='vectorstores')
    op.drop_table('vectorstores')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
